version: 0.2
env:
  parameter-store:
    DOCKERPASSWORD: /CodeBuild/dockerLoginPassword
    DOCKERUSERNAME: /CodeBuild/dockerLoginUsername
phases:
  install:
    commands:
      - echo Entered the install phase...
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase...
      - ls -ld -- */
      - docker image build -t $DOCKERUSERNAME/supergoondiscordbot:csharp .
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - docker login -u $DOCKERUSERNAME -p $DOCKERPASSWORD
      - docker image push $DOCKERUSERNAME/supergoondiscordbot:csharp 
      - echo Build completed on `date`
